name: 'ARMCortexM Test Generator'
description: 'AI-powered autonomous test generator using Claude. Generates and validates assembly tests.'
author: 'MatejGomboc-Claude-MCP'

inputs:
  functions:
    description: 'Space-separated list of function names to generate tests for (e.g., "setBit clearBit")'
    required: true
  anthropic-api-key:
    description: 'Anthropic API key for Claude'
    required: true
  max-cost:
    description: 'Maximum API cost in USD (default: 50.0)'
    required: false
    default: '50.0'
  repo-path:
    description: 'Path to repository (default: current directory)'
    required: false
    default: '.'
  module:
    description: 'Module to test (default: bit_utils). Examples: bit_utils, intrinsics/barriers'
    required: false
    default: 'bit_utils'

runs:
  using: 'composite'
  steps:
    - name: Verify Python availability
      shell: bash
      run: |
        if ! command -v python3 &> /dev/null; then
          echo "❌ ERROR: Python 3 not found in container!"
          echo "Please ensure you're using the ARMCortexM-CppLib DevEnv container"
          exit 1
        fi
        python3 --version
    
    - name: Install dependencies
      shell: bash
      run: |
        cd ${{ github.action_path }}
        python3 -m pip install --upgrade pip
        python3 -m pip install -r requirements.txt
    
    - name: Run autonomous test generator
      shell: bash
      env:
        ANTHROPIC_API_KEY: ${{ inputs.anthropic-api-key }}
      run: |
        cd ${{ github.action_path }}
        python3 autonomous_test_generator.py \
          --functions ${{ inputs.functions }} \
          --repo-path ${{ inputs.repo-path }} \
          --module ${{ inputs.module }} \
          --max-cost ${{ inputs.max-cost }}
    
    - name: Upload test generation log
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: testgen-log
        path: testgen.log
        retention-days: 7

branding:
  icon: 'cpu'
  color: 'blue'
